### 3. Let x = 10 and y = 3. Write a line of code that will make each of the following assignments.

In [1]:
import math

x = 10
y = 3

u = x + y
v = x * y
w = x / y
z = math.sin(x)
r = 8 * math.sin(x)
s = 5 * math.sin(x * y)
p = x**y

print(f"u = {u}\nv = {v}\nw = {w}\nz = {z} \nr = {r} \ns = {s} \np = {p}")

u = 13
v = 30
w = 3.3333333333333335
z = -0.5440211108893698 
r = -4.352168887114958 
s = -4.940158120464309 
p = 1000


### 4. Show all the variables in the jupyter notebook after you finsh problem 3.

In [2]:
%whos

Variable   Type      Data/Info
------------------------------
math       module    <module 'math' (built-in)>
p          int       1000
r          float     -4.352168887114958
s          float     -4.940158120464309
u          int       13
v          int       30
w          float     3.3333333333333335
x          int       10
y          int       3
z          float     -0.5440211108893698


### 5. Assign string "123" to the varaible S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the type function.

In [3]:
S = "123"
N = float(S)

print(f"N = {N}\nS is a {type(S)}\nN is {type(N)}")

N = 123.0
S is a <class 'str'>
N is <class 'float'>


### 6. Assign the string "HELLO" to the variable s1 and the string "hello" to the variable s2. Use the == operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the lower method is used on s1. Use the == operator to show that s1 and s2 are equal if upper method is used on s2.

In [4]:
s1 = "HELLO"
s2 = "hello"

print(f"s1 == s2 is {s1 == s2}\ns1.lower() == s2 is {s1.lower() == s2}\ns1 == s2.upper() is {s1 == s2.upper()}\n")

s1 == s2 is False
s1.lower() == s2 is True
s1 == s2.upper() is True



### 7. use the print function to generate the following strings

In [5]:
word1 = "Engineering"
word2 = "Book"


print(f"The world \"{word1}\" has {len(word1)} leters.")
print(f"The word \"{word2}\" has {len(word2)} leters.")


The world "Engineering" has 11 leters.
The word "Book" has 4 leters.


### 8. Check if "python" is in "Python is great!"

In [6]:
string1 = "Python is great"
string2 = "Python"

if string2 in string1:
    print("\"python\" is in \"Python is great!\"")
else:
    print("\"python\" is not \"Python is great!\"")

"python" is in "Python is great!"


### 9. Get the last word "great" from "Python is great!"

In [7]:
string1 = "Python is great"

list1 = string1.split()

location = list1.index("great")

print(f"The word {list1[location]} is found in location {location} of the list.")


The word great is found in location 2 of the list.


### 10. Assign list [ 1, 8, 9, 15] to a variable list_a and insert 2 at index 1 using the insert method. Append 4 to the list_a using the append method.

In [8]:
list_a = [1 , 8, 9, 15]

list_a.insert(1,2)
list_a.append(4)

print(f"The following list is: {list_a}")

The following list is: [1, 2, 8, 9, 15, 4]


### 11. Sort the list_a in problem 10 in ascending order

In [9]:
list_a = [1 , 8, 9, 15]

list_a.insert(1,2)
list_a.append(4)

print(f"The following list is: {list_a}")
list_a.sort()
print(f"The following list in ascending order is: {list_a}")


The following list is: [1, 2, 8, 9, 15, 4]
The following list in ascending order is: [1, 2, 4, 8, 9, 15]


### 12. Turn "Python is great!" into a list

In [10]:
string1 = "Python is great"

list1 = string1.split()

print(f"\"Python is great!\" as a list is: {list1}")


"Python is great!" as a list is: ['Python', 'is', 'great']


### 13. Create one tuple with element "One", and assign it to tuple_a.

In [11]:
tuple_a = ("One",1)
print(tuple_a)

('One', 1)


### 14. Get the second element in the tuple_a in problem 13.

In [12]:
print(tuple_a[1])

1


### 15. Get the unique element from (2, 3, 2, 3, 1, 2, 5).

In [13]:
element = (2, 3, 2, 3, 1, 2, 5)

print(set(element))

{1, 2, 3, 5}


### 16. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Obtain the Following:
* Union of set_a and set_b
* intersection of set_a and set_b
* difference of set_a to set_b using difference method

In [14]:
set_a = {2, 3, 2}
set_b = {1, 2, 3}


union = set_a.union(set_b)
intersection = set_a.intersection(set_b)
difference = set_a.difference(set_b)

print(f"Union = {union}\nIntersection = {intersection}\nDifference = {difference}")

Union = {1, 2, 3}
Intersection = {2, 3}
Difference = set()


### 17. Create a dictionary that has the keys "A", "B", "C" with values "a", "b", "c" individually. Print all the keys in the dictionary.

In [15]:
dictionary = {"A":"a" , "B":"b", "C":"c"}
print(dictionary.keys())

dict_keys(['A', 'B', 'C'])


### 18. Check if keys "B" is in the dictionary defined in Problem 17.

In [16]:
if "B" in dictionary:
    print("B is in dictionary")
else:
    print("B is not in dictionary")

B is in dictionary


### 19. Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y = [2, 3, 4, 1, 2, 3]. Compute the assignments from problem 3

In [17]:
import math
import numpy

x = numpy.array([1, 4, 3, 2, 9, 4])
y = numpy.array([2, 3, 4, 1, 2, 3])

u = x + y
v = x * y
w = x / y
z = numpy.sin(x)
r = 8 * numpy.sin(x)
s = 5 * numpy.sin(x * y)
p = x**y

print(f"u = {u}\nv = {v}\nw = {w}\nz = {z} \nr = {r} \ns = {s} \np = {p}")



u = [ 3  7  7  3 11  7]
v = [ 2 12 12  2 18 12]
w = [0.5        1.33333333 0.75       2.         4.5        1.33333333]
z = [ 0.84147098 -0.7568025   0.14112001  0.90929743  0.41211849 -0.7568025 ] 
r = [ 6.73176788 -6.05441996  1.12896006  7.27437941  3.29694788 -6.05441996] 
s = [ 4.54648713 -2.68286459 -2.68286459  4.54648713 -3.75493623 -2.68286459] 
p = [ 1 64 81  2 81 64]


### 20. Generate an array with size 100 evenly spaced between -10 to 10 using linspace function in NumPy.

In [18]:
array = numpy.linspace(-10,10,num = 100)

print(array)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

### 21. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command tha will return an array consisting of all the elements of array_a that are larger than zero.

In [19]:
import numpy

array_a = numpy.array([-1, 0, 1, 2, 0, 3])
array_b = array_a[array_a>0]

print(array_b)


[1 2 3]


### 22. create an array and calculate its transpose.

In [20]:
import numpy
y = numpy.array([[3, 5, 5],[2, 2, 5],[3, 8, 9]])
print(numpy.transpose(y))


[[3 2 3]
 [5 2 8]
 [5 5 9]]


### 23. Create a 2 x 4 zero array.

In [21]:
import numpy
ZeroArray = numpy.zeros((2,4))
print(ZeroArray)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 24. Change the second coloumn in the above array to 1.

In [22]:
import numpy
ZeroArray[0,1]=1
ZeroArray[1,1]=1
print(ZeroArray)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


### 25. Write a magic command to clear all the variables in the Jupyter notebook.

In [23]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y
