### SP1 Write code to perform a dot product on two vectors with any number of dimensions. Do not use built-in functions in python/numpy to do this. Demonstrate it works correctly using a problem from HW 7.

In [5]:
def DotProduct():
    A = []
    B = []
    AB = 0
    index = int(input("How many indexs in matrix "))
    for i in range(0, index):
        A.append(float(input(f"Input value for A{i+1} ")))
    for i in range(0,index):    
        B.append(float(input(f"Input value for B{i+1} ")))
    print(f"A matrix is {A}")
    print(f"B matrix is {B}")
    for i in range(0, index):
        AB += (A[i] * B[i])
    print(f"A dot B is {AB}")
    return
DotProduct()

How many indexs in matrix 4
Input value for A1 7.2
Input value for A2 -4.3
Input value for A3 0.6
Input value for A4 1.7
Input value for B1 -11
Input value for B2 11.8
Input value for B3 2.4
Input value for B4 -1.9
A matrix is [7.2, -4.3, 0.6, 1.7]
B matrix is [-11.0, 11.8, 2.4, -1.9]
A dot B is -131.73


### SP2 Write code to perform a vector cross product. Write this to work for three dimensions. Use vectors from HW 7 to demonstrate this works. Work the problem out by hand to verify the answer is correct. Note the output in this case is a vector.

In [6]:
import numpy as np
def cross_product_3x3():
    dimension = 3
    A = np.empty([dimension,dimension])
    B = np.empty([dimension,dimension])
    for i in range(0, dimension):
        for j in range(0,dimension):
            A[i][j] = float(input(f"Input value for A{i}{j}: "))
    for i in range(0, dimension):
        for j in range(0,dimension):
            B[i][j] = float(input(f"Input value for B{i}{j}: "))
    print(f"A matrix is\n{A}")
    print(f"B matrix is\n{B}")
    print(f"Cross vector is\n{np.cross(A,B)}")
    return
cross_product_3x3()

Input value for A00: 1
Input value for A01: 3
Input value for A02: 0
Input value for A10: 2
Input value for A11: -1
Input value for A12: 0
Input value for A20: 3
Input value for A21: 2
Input value for A22: 0
Input value for B00: 0
Input value for B01: 0
Input value for B02: 0
Input value for B10: 0
Input value for B11: 0
Input value for B12: 0
Input value for B20: 2
Input value for B21: 5
Input value for B22: 7
A matrix is
[[ 1.  3.  0.]
 [ 2. -1.  0.]
 [ 3.  2.  0.]]
B matrix is
[[0. 0. 0.]
 [0. 0. 0.]
 [2. 5. 7.]]
Cross vector is
[[  0.   0.   0.]
 [ -0.   0.   0.]
 [ 14. -21.  11.]]


### SP3 Write code to perform matrix multiplication. Note the matrices may be any number of dimensions (as long as you can actually multiply them). 

In [7]:
import numpy as np
def matrix_multi():
    Arows = int(input("How many Rows in matrix A "))
    Acols = int(input("How many Columns in matrix A "))
    Brows = int(input("How many Rows in matrix B "))
    Bcols = int(input("How many Columns in matrix B "))
    A = np.empty([Arows, Acols])
    B = np.empty([Brows, Bcols])
    AB = np.empty([Arows, Bcols])
    for i in range(0, Arows):
        for j in range(0, Acols):
            A[i][j] = ((float(input(f"Input value for A{i + 1}{j + 1} "))))
    for i in range(0, Brows):
        for j in range(0, Bcols):
            B[i][j] = (float(input(f"Input value for B{i + 1}{j + 1} ")))
    print(f"A matrix is\n{A}")
    print(f"B matrix is\n{B}")
    for i in range(0, Arows):
        for j in range(0, Bcols):
            sum = 0
            for k in range(0, Bcols):
                sum += (A[i][k]) * (B[k][j])
            AB[i][j] = (sum)
    print(f"A multiplied by B is\n{AB}")
    return
matrix_multi()

How many Rows in matrix A 3
How many Columns in matrix A 3
How many Rows in matrix B 3
How many Columns in matrix B 3
Input value for A11 1
Input value for A12 3
Input value for A13 0
Input value for A21 2
Input value for A22 -1
Input value for A23 0
Input value for A31 3
Input value for A32 2
Input value for A33 0
Input value for B11 0
Input value for B12 0
Input value for B13 0
Input value for B21 0
Input value for B22 0
Input value for B23 0
Input value for B31 2
Input value for B32 5
Input value for B33 7
A matrix is
[[ 1.  3.  0.]
 [ 2. -1.  0.]
 [ 3.  2.  0.]]
B matrix is
[[0. 0. 0.]
 [0. 0. 0.]
 [2. 5. 7.]]
A multiplied by B is
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### SP4 Write code to perform Cramer's rule for a 3x3 matrix problem. Demonstrate this works by using your code to solve the 3x3 Cramer's rule problem from HW7.

In [8]:
import numpy as np

def cramers_rule():
    Arows = int(input("How many Rows in matrix A "))
    Acols = int(input("How many Columns in matrix A "))
    Brows = int(input("How many Rows in matrix B "))
    Bcols = int(input("How many Columns in matrix B "))
    A = np.empty([Arows, Acols])
    B = np.empty([Brows, Bcols])
    AB = np.empty([Arows, Bcols])
    for i in range(0, Arows):
        for j in range(0, Acols):
            A[i][j] = ((float(input(f"Input value for A{i + 1}{j + 1} "))))
    for i in range(0, Brows):
        for j in range(0, Bcols):
            B[i][j] = (float(input(f"Input value for B{i + 1}{j + 1} ")))
    print(f"A matrix is\n{A}")
    print(f"B matrix is\n{B}")
    D = ((A[0][0] * A[1][1] * A[2][2]) + (A[0][1] * A[1][2] * A[2][0]) + (A[0][2] * A[1][0] * A[2][1])) - (
            (A[0][0] * A[1][2] * A[2][1]) + (A[0][1] * A[1][0] * A[2][2]) + (A[0][2] * A[1][1] * A[2][0]))
    Dx = ((B[0] * A[1][1] * A[2][2]) + (A[0][1] * A[1][2] * B[2]) + (A[0][2] * B[1] * A[2][1])) - (
            (B[0] * A[1][2] * A[2][1]) + (A[0][1] * B[1] * A[2][2]) + (A[0][2] * A[1][1] * B[2]))

    Dy = ((A[0][0] * B[1] * A[2][2]) + (B[0] * A[1][2] * A[2][0]) + (A[0][2] * A[1][0] * B[2])) - (
            (A[0][0] * A[1][2] * B[2]) + (B[0] * A[1][0] * A[2][2]) + (A[0][2] * B[1] * A[2][0]))

    Dz = ((A[0][0] * A[1][1] * B[2]) + (A[0][1] * B[1] * A[2][0]) + (B[0] * A[1][0] * A[2][1])) - (
            (A[0][0] * B[1] * A[2][1]) + (A[0][1] * A[1][0] * B[2]) + (B[0] * A[1][1] * A[2][0]))
    X = Dx / D
    Y = Dy / D
    Z = Dz / D
    print(f"X = {X}\nY = {Y}\nZ = {Z}")
    return

cramers_rule()

How many Rows in matrix A 3
How many Columns in matrix A 3
How many Rows in matrix B 3
How many Columns in matrix B 1
Input value for A11 1
Input value for A12 2
Input value for A13 3
Input value for A21 3
Input value for A22 1
Input value for A23 -3
Input value for A31 -3
Input value for A32 4
Input value for A33 7
Input value for B11 -5
Input value for B21 4
Input value for B31 -7
A matrix is
[[ 1.  2.  3.]
 [ 3.  1. -3.]
 [-3.  4.  7.]]
B matrix is
[[-5.]
 [ 4.]
 [-7.]]
X = [-1.]
Y = [1.]
Z = [-2.]


### SP5 Write code to perform back substitution. Note use examples from the lecture notes to test your code.

In [9]:
import numpy as np

A = np.array([[1,-3,1],[2,-8,8],[-6,3,-15]])
B = np.array([4,-2,9])
import numpy as np
def gauss_elimin(A,B):
    n = len(B)
    for i in range(0,n-1):
        for j in range(i+1,n):
            if A[j,i] != 0.0:
                k = A[j,i]/A[i,i]
                A[j,i+1:n] = A[j,i+1:n] - k*A[i,i+1:n]
                B[j] = B[j] - k*B[i]
    for k in range(n-1,-1,-1):
        B[k] = (B[k] - np.dot(A[k,k+1:n],B[k+1:n]))/A[k,k]
    return B
gauss_elimin(A,B)

array([ 3, -1, -2])

### SP6 Write code to perform addition and subtraction for two matrices. Demonstrate that your code works with a problem from HW 7.

In [10]:
import numpy as np

def add_subtract():
    Arows = int(input("How many Rows in matrix A "))
    Acols = int(input("How many Columns in matrix A "))
    Brows = int(input("How many Rows in matrix B "))
    Bcols = int(input("How many Columns in matrix B "))
    A = np.empty([Arows, Acols])
    B = np.empty([Brows, Bcols])
    AB = np.empty([Arows, Bcols])
    for i in range(0, Arows):
        for j in range(0, Acols):
            A[i][j] = ((float(input(f"Input value for A{i + 1}{j + 1} "))))
    for i in range(0, Brows):
        for j in range(0, Bcols):
            B[i][j] = (float(input(f"Input value for B{i + 1}{j + 1} ")))
    print(f"A matrix is\n{A}")
    print(f"B matrix is\n{B}")
    print(f"A + B is\n{A+B}")
    print(f"A - B is\n{A-B}")
    return

add_subtract()

How many Rows in matrix A 1
How many Columns in matrix A 4
How many Rows in matrix B 1
How many Columns in matrix B 4
Input value for A11 7.2
Input value for A12 -4.3
Input value for A13 0.6
Input value for A14 1.7
Input value for B11 -11.0
Input value for B12 11.8
Input value for B13 2.4
Input value for B14 -1.9
A matrix is
[[ 7.2 -4.3  0.6  1.7]]
B matrix is
[[-11.   11.8   2.4  -1.9]]
A + B is
[[-3.8  7.5  3.  -0.2]]
A - B is
[[ 18.2 -16.1  -1.8   3.6]]
